export const TOKENS = [
  {
    id: '1',
    tokenName: 'BTC',
    image: '/static/images/tokens/btc.png',
    primary: 'BTC',
    secondary: 'Bitcoin',
    numDecimalPlaces: 8,
    data: 'set_btc',
  },
  {
    id: '2',
    tokenName: 'ETH',
    image: '/static/images/tokens/eth.png',
    primary: 'ETH',
    secondary: 'Ethereum',
    numDecimalPlaces: 8,
    data: 'set_eth',
  },
  {
    id: '3',
    tokenName: 'PDT',
    image: '/static/images/tokens/pdt.svg',
    primary: 'PDT',
    secondary: 'Paradise Token',
    numDecimalPlaces: 3,
    data: 'set_pdt',
  },
  {
    id: '4',
    tokenName: 'XRP',
    image: '/static/images/tokens/xrp.png',
    primary: 'XRP',
    secondary: 'Ripple',
    numDecimalPlaces: 6,
    data: 'set_xrp',
  },
  {
    id: '5',
    tokenName: 'ATOM',
    image: '/static/images/tokens/atom.png',
    primary: 'ATOM',
    secondary: 'Cosmos',
    numDecimalPlaces: 7,
    data: 'set_atom',
  },
  {
    id: '6',
    tokenName: 'SOL',
    image: '/static/images/tokens/sol.png',
    primary: 'SOL',
    secondary: 'Solana',
    numDecimalPlaces: 8,
    data: 'set_sol',
  },
  {
    id: '7',
    tokenName: 'BNB',
    image: '/static/images/tokens/bnb.png',
    primary: 'BNB',
    secondary: 'Binance Coin',
    numDecimalPlaces: 8,
    data: 'set_bnb',
  },
  {
    id: '8',
    tokenName: 'ADA',
    image: '/static/images/tokens/ada.png',
    primary: 'ADA',
    secondary: 'Cardano',
    numDecimalPlaces: 8,
    data: 'set_ada',
  },
  {
    id: '9',
    tokenName: 'DOT',
    image: '/static/images/tokens/dot.png',
    primary: 'DOT',
    secondary: 'Polkadot',
    numDecimalPlaces: 8,
    data: 'set_dot',
  },
  {
    id: '10',
    tokenName: 'FIL',
    image: '/static/images/tokens/fil.png',
    primary: 'FIL',
    secondary: 'Filecoin',
    numDecimalPlaces: 7,
    data: 'set_fil',
  },
  {
    id: '11',
    tokenName: 'AVAX',
    image: '/static/images/tokens/avax.png',
    primary: 'AVAX',
    secondary: 'Avalanche',
    numDecimalPlaces: 8,
    data: 'set_avax',
  },
  {
    id: '12',
    tokenName: 'MATIC',
    image: '/static/images/tokens/matic.png',
    primary: 'MATIC',
    secondary: 'Polygon',
    numDecimalPlaces: 6,
    data: 'set_matic',
  },
  {
    id: '13',
    tokenName: 'SAND',
    image: '/static/images/tokens/sand.png',
    primary: 'SAND',
    secondary: 'The Sandbox',
    numDecimalPlaces: 6,
    data: 'set_sand',
  },
  {
    id: '14',
    tokenName: 'LTC',
    image: '/static/images/tokens/ltc.png',
    primary: 'LTC',
    secondary: 'Litecoin',
    numDecimalPlaces: 6,
    data: 'set_ltc',
  },
  {
    id: '15',
    tokenName: 'TRX',
    image: '/static/images/tokens/trx.png',
    primary: 'TRX',
    secondary: 'TRON',
    numDecimalPlaces: 3,
    data: 'set_trx',
  },
  {
    id: '16',
    tokenName: 'LINK',
    image: '/static/images/tokens/link.png',
    primary: 'LINK',
    secondary: 'Chainlink',
    numDecimalPlaces: 5,
    data: 'set_link',
  },
  {
    id: '17',
    tokenName: 'DOGE',
    image: '/static/images/tokens/doge.png',
    primary: 'DOGE',
    secondary: 'DOGE',
    numDecimalPlaces: 3,
    data: 'set_doge',
  },
  {
    id: '18',
    tokenName: 'XMR',
    image: '/static/images/tokens/xmr.png',
    primary: 'XMR',
    secondary: 'Monero',
    numDecimalPlaces: 7,
    data: 'set_xmr',
  },
];
